name: Make Apk CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Build-Apk:
    runs-on: ubuntu-20.04 # That is the latest OS version available today
    steps:
    - name: Cache fontforge and extra dependencies
      id: cache_localbin
      uses: actions/cache@v2
      with:
        path: /usr/local/bin
        key: usr-local-bin
    - name: Install latest FontForge version (using AppImage)
      if: steps.cache_localbin.outputs.cache-hit != 'true'
      run: |
        # Get most recent version of FontForge
        # Using AppImage there is no dependecy problem, it is the latest version and it's easier to cache
        # -------
        cd /usr/local/bin
        sudo wget -c -N https://github.com/fontforge/fontforge/releases/download/20220308/FontForge-2022-03-08-582bd41-x86_64.AppImage
        sudo chmod +x ./FontForge-2022-03-08-582bd41-x86_64.AppImage
        sudo ln --symbolic --force /usr/local/bin/FontForge-2022-03-08-582bd41-x86_64.AppImage /usr/local/bin/fontforge
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Cache debug certificate
      uses: actions/cache@v2
      with:
        path: _build/debug.keystore
        key: debug-keystore
    - name: Build
      run: make
    - name: Save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: _build/*.apk
