name: Make Apk CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Build-Apk:
    runs-on: ubuntu-latest
    steps:
    - name: Install nix
      uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Cache Nix store
      uses: actions/cache@v2
      with:
        path: /nix
        key: nix-store
    - name: Install external dependencies
      run: nix-env -f '<nixpkgs>' -i fontforge
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Cache debug certificate
      uses: actions/cache@v2
      with:
        path: _build/debug.keystore
        key: debug-keystore
    - name: Build
      run: make
    - name: Save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: _build/*.apk
