name: Make Apk CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Build-Apk:
    runs-on: ubuntu-20.04 # That is the latest OS version available today
    steps:
    # Dirty OS upgrade to get newer version of FontForge
    # - name: Tweaks to get more recent version of fontforge
    #   run: |
    #     # Dirty: Get a more recent version of fontforge
    #     sudo sed -i 's/focal/impish/g' /etc/apt/sources.list
    #     sudo apt-get update -y
    # - name: Install external dependencies and cache them
    #   uses: awalsh128/cache-apt-pkgs-action@v1
    #   with:
    #     packages: fontforge fontforge-common libfontforge4 libpython3.9 libgtk-3-0
    #     version: 1.0
    - name: Install external dependencies and cache them
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: fontforge fontforge-common libfontforge3 libgdraw6 libc6 libpython3.8 libuninameslist1 libgtk-3-0
        version: 1.0
    - name: Try to install fontforge again to get any missing non cached dependency
      run: sudo apt-get install -y fontforge
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '11'
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Cache debug certificate
      uses: actions/cache@v2
      with:
        path: _build/debug.keystore
        key: debug-keystore
    - name: Build
      run: make
    - name: Save debug apk
      uses: actions/upload-artifact@v2
      with:
        name: debug apk
        path: _build/*.apk
