name: Make APKs CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Build-Apks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install FontForge
        run: |
          sudo apt-get update
          sudo apt-get -y install fontforge
      - name: Build APKs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - name: Artifact naming
        run: |
          artifact="${{github.repository_owner}} ${{github.ref_name}}"
          artifact="${artifact//\//-}" # replace slashes
          echo "artifact=${artifact}" >> $GITHUB_ENV
      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: "${{env.artifact}} debug_apk"
          path: app/build/outputs/apk/debug/*.apk
      - name: Upload unsigned release APK
        uses: actions/upload-artifact@v3
        with:
          name: "${{env.artifact}} unsigned_release_apk"
          path: app/build/outputs/apk/release/*.apk
